"""Section-list mode (LLM-COP-5) — /muokkaa/osiot, the row fragment route,
and the reorder / add / hide-show / restore API, against the real routes and
the app's own DB file.

Governing specs cp-main-edit-sections (screen) and cp-section-row (component,
role: component). One test — or one parametrized case — per addressed
criterion, each citing its spec address. Neither spec states a testid, so
nothing here invents a data-testid selector; is-visible criteria are proven as
presence in the served document, matching tests/test_page.py's convention.

Every contains-text assertion goes through element_text() on a real classed
element, never as a raw substring of the document. That is load-bearing rather
than stylistic: the page carries a script#bootstrap JSON blob holding the whole
field schema, so a raw "Nostolause" in html would pass off the blob and prove
nothing. element_text only collects text inside a matched start tag
(tests/conftest.py:100-124), so it can never reach script content.

What this file deliberately does NOT cover, and why:

* nostolause-label, leipateksti-label, nostolause-textarea and
  leipateksti-textarea are generated by app/static/section-form.js into a
  server-rendered-empty <form class="section-form">. No test in this
  repository executes JavaScript, so they are unreachable here and are proven
  only by the live browser run. Asserting them as raw substrings would pass
  off the bootstrap blob for one and could never pass for the other.
* koulutus-label / kokemus-label / osaaminen-label and their three sibling
  inputs are not satisfied by this change at all: tietoa.facts is an
  unlabelled positional list (app/fields.py:30) whose seeded values are
  "Käynnit 45-90 min" and friends (app/seed.py:57-59), not a degree, a span of
  years and a specialism. Reported unsatisfied rather than faked with a
  positional label that would sit over the wrong value.
* esikatselu-card's second criterion, "Olen työskennellyt puheterapeuttina",
  is sample data that no seeded payload holds. Its heading half is asserted
  here byte-exact; its body half is proven live by typing the sentence in and
  watching it reach the card. A fixture planting the sentence would prove
  nothing.

The expanded-editor criteria are asserted against GET /muokkaa/osiot/rivi/<id>,
a one-row document where element_text's first-match is unambiguous — on the
page every row carries the same chrome, so the first .exp-title is hero's.
test_the_page_row_is_byte_identical_to_the_fragment is what carries those
assertions back to the page document.
"""

import ast
import copy
import json
import pathlib
import re
from html.parser import HTMLParser
from urllib.parse import urlparse

import pytest
from flask import render_template_string

from app import db as database
from app.fields import ANCHORS, FIELDS
from app.sanitize import validate_payload
from app.sections import visible_sections
from app.seed import SEED_SECTIONS
from app.summary import blank_payload, summarize
from tests.conftest import delete_section, element_text, section_rows

SEED_BY_KIND = dict(SEED_SECTIONS)
JSON_ACCEPT = {"Accept": "application/json"}

DISCLAIMER = "Muutokset näkyvät julkisella sivulla vasta julkaisun jälkeen."
HERO_SUMMARY = "Muotokuva, otsikko, ingressi, 2 painiketta"


# --- helpers -----------------------------------------------------------------


def row_id(app, kind):
    return next(r["id"] for r in section_rows(app) if r["kind"] == kind)


def kinds_in_position_order(app):
    return [r["kind"] for r in section_rows(app)]


_LI_TOKEN = re.compile(r"<li\b|</li\s*>", re.IGNORECASE)


def outer_li(html, section_id):
    """The whole <li class="section-row" data-section-id="N"> … </li>.

    Depth-aware on purpose: fact_card and service_card emit <li>, so the hero
    and palvelut rows nest lists inside their preview cards and a naive scan to
    the first </li> truncates them (measured: hero 2411 of 3767 bytes). The
    tietoa row happens to have none today, but a ⋯ menu rendered as list items
    would give it some tomorrow.
    """
    start = html.index(f'<li class="section-row" data-section-id="{section_id}"')
    depth = 0
    for match in _LI_TOKEN.finditer(html, start):
        if match.group(0).startswith("</"):
            depth -= 1
            if depth == 0:
                return html[start : match.end()]
        else:
            depth += 1
    raise AssertionError(f"unclosed <li> for section {section_id}")


def positions(app):
    return {r["id"]: r["position"] for r in section_rows(app)}


def put_order(admin, ids):
    return admin.put("/api/sections/order", json={"ids": ids},
                     headers=JSON_ACCEPT)


def publish(admin):
    return admin.post("/api/publish", headers=JSON_ACCEPT)


def public_html(app):
    return app.test_client().get("/").get_data(as_text=True)


@pytest.fixture
def osiot_html(logged_in_admin):
    response = logged_in_admin.get("/muokkaa/osiot")
    assert response.status_code == 200
    return response.get_data(as_text=True)


@pytest.fixture
def tietoa_fragment(logged_in_admin, app):
    response = logged_in_admin.get(
        f"/muokkaa/osiot/rivi/{row_id(app, 'tietoa')}"
    )
    assert response.status_code == 200
    return response.get_data(as_text=True)


# --- Step 1: the summaries and the blank payload -----------------------------


def test_hero_summary_is_the_row_aloitusosio_criterion_byte_exact():
    """cp-main-edit-sections.sections-list.row-aloitusosio / cp-section-row
    row-summary — contains-text "Muotokuva, otsikko, ingressi, 2 painiketta".

    Asserted on the summary generator over the seeded hero payload, so the
    string is produced from data rather than written into a template.
    """
    assert summarize("hero", SEED_BY_KIND["hero"]) == HERO_SUMMARY


def test_palvelut_summary_counts_the_stored_list_and_declines_the_noun():
    # The summary counts the payload, not the schema: three seeded services
    # (app/seed.py:66-70) read "3 palvelukorttia", one reads the singular.
    assert summarize("palvelut", SEED_BY_KIND["palvelut"]) == "3 palvelukorttia"
    assert summarize("palvelut", {"services": ["Yksi"]}) == "1 palvelukortti"
    assert summarize("palvelut", {"services": []}) == "0 palvelukorttia"


def test_hero_summary_counts_the_buttons_that_carry_text():
    payload = copy.deepcopy(SEED_BY_KIND["hero"])
    payload["services_label"] = ""
    assert summarize("hero", payload) == "Muotokuva, otsikko, ingressi, 1 painike"


@pytest.mark.parametrize("kind", sorted(FIELDS))
def test_blank_payload_validates_and_renders_for_every_kind(app, kind):
    """A precondition of the preview card, not a formality: a new section's
    card renders before anyone has typed into it, and page.html dereferences
    every field a macro names — a missing key raises UndefinedError.
    """
    blank = blank_payload(kind)
    assert set(blank) == set(FIELDS[kind]), "every declared field, incl. unlabelled"
    _clean, errors = validate_payload(kind, blank)
    assert errors == {}

    with app.test_request_context("/"):
        html = render_template_string(
            "{% import 'page.html' as public with context %}"
            "{{ public[kind](payload) }}",
            kind=kind,
            payload=blank,
            anchors=ANCHORS,
        )
    assert html.strip(), f"{kind} rendered nothing"


# --- the session gate (the mode is admin-only) -------------------------------


@pytest.mark.parametrize(
    "path", ["/muokkaa/osiot", "/muokkaa/osiot/rivi/1"]
)
def test_anonymous_get_redirects_to_yllapito(client, path):
    response = client.get(path)
    assert response.status_code == 302
    assert urlparse(response.headers["Location"]).path == "/yllapito"


@pytest.mark.parametrize(
    "method,path,body",
    [
        ("put", "/api/sections/order", {"ids": [1]}),
        ("post", "/api/sections", {"kind": "sijainti"}),
        ("post", "/api/sections/1/state", {"state": "hidden"}),
        ("post", "/api/sections/1/restore", None),
    ],
)
def test_anonymous_json_api_gets_401(client, method, path, body):
    response = getattr(client, method)(
        path, json=body if body is not None else {}, headers=JSON_ACCEPT
    )
    assert response.status_code == 401
    assert response.get_json() == {"error": "unauthorized"}


@pytest.mark.parametrize(
    "method,path,body",
    [
        ("get", "/muokkaa/osiot/rivi/9999", None),
        ("post", "/api/sections/9999/state", {"state": "hidden"}),
        ("post", "/api/sections/9999/restore", None),
    ],
)
def test_unknown_section_id_is_404(logged_in_admin, method, path, body):
    kwargs = {"headers": JSON_ACCEPT}
    if body is not None:
        kwargs["json"] = body
    response = getattr(logged_in_admin, method)(path, **kwargs)
    assert response.status_code == 404


# --- Step 4: the served /muokkaa/osiot document ------------------------------

PAGE_TEXT_CRITERIA = [
    ("cp-main-edit-sections.sections-topbar.sections-mode",
     "span", "topbar-mode", "Muokkaustila"),
    ("cp-main-edit-sections.sections-topbar.sections-mode",
     "span", "topbar-mode", "osiot"),
    ("cp-main-edit-sections.sections-topbar.sections-count",
     "span", "topbar-page", "Etusivu"),
    ("cp-main-edit-sections.sections-topbar.jarjesta-link",
     "a", "jarjesta-link", "Järjestä osiot"),
    ("cp-main-edit-sections.sections-topbar.sections-esikatsele",
     "a", "esikatsele-button", "Esikatsele"),
    ("cp-main-edit-sections.sections-topbar.sections-julkaise",
     "button", "julkaise-button", "Julkaise"),
    ("cp-main-edit-sections.add-section-button",
     "button", "add-section-button", "Lisää osio"),
    # row-aloitusosio uses cp-section-row; hero is SEED_SECTIONS[0] and so
    # position 1, which is why first-match is the exemplar row the spec names.
    ("cp-main-edit-sections.sections-list.row-aloitusosio/row-title",
     "span", "row-title", "Aloitusosio"),
    ("cp-main-edit-sections.sections-list.row-aloitusosio/row-summary",
     "span", "row-summary", HERO_SUMMARY),
    ("cp-main-edit-sections.sections-list.row-aloitusosio/row-status-badge",
     "span", "row-status-badge", "Julkaistu"),
    ("cp-section-row.row-edit-button",
     "button", "row-edit-button", "Muokkaa"),
]


@pytest.mark.parametrize(
    "address,tag,cls,expected",
    [
        pytest.param(a, t, c, e, id=f"{a}:{e}")
        for a, t, c, e in PAGE_TEXT_CRITERIA
    ],
)
def test_osiot_document_contains_text(osiot_html, address, tag, cls, expected):
    text = element_text(osiot_html, tag, cls)
    assert text is not None, f"{address}: no <{tag} class={cls}> in the document"
    assert expected in text, f"{address}: {expected!r} not in {text!r}"


@pytest.mark.parametrize(
    "address,tag,cls",
    [
        ("cp-section-row.row-drag-handle", "span", "row-drag-handle"),
        ("cp-main-edit-sections.sections-list", "ul", "sections-list"),
        ("cp-main-edit-sections.sections-list.row-aloitusosio",
         "li", "section-row"),
    ],
)
def test_osiot_document_renders_the_is_visible_regions(
    osiot_html, address, tag, cls
):
    assert element_text(osiot_html, tag, cls) is not None, address


def test_sections_list_holds_one_row_per_section_in_position_order(
    osiot_html, app
):
    """cp-main-edit-sections.sections-list — "one row per section of the page,
    in the order the page shows them"."""
    rendered = re.findall(r'<li class="section-row" data-section-id="(\d+)"',
                          osiot_html)
    assert [int(i) for i in rendered] == [r["id"] for r in section_rows(app)]
    assert len(rendered) == 6


def test_sections_count_is_rendered_from_data_not_from_the_mockup(
    logged_in_admin, app
):
    """cp-main-edit-sections.sections-count — the mockup reads "5 osiota" over
    six rows and its own note calls the count data, so it is rendered from the
    store and the plural agrees with it."""
    text = element_text(
        logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True),
        "span", "topbar-page",
    )
    assert text == "Etusivu · 6 osiota"

    for kind in ("tietoa", "palvelut", "vastaanottoajat", "yhteydenotto",
                 "sijainti"):
        delete_section(app, kind)
    text = element_text(
        logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True),
        "span", "topbar-page",
    )
    assert text == "Etusivu · 1 osio"


def test_importing_page_html_leaks_no_public_chrome_into_the_screen(osiot_html):
    """The preview cards reuse page.html's macros, and importing it with
    context executes that template's module body — the header, the nav and the
    footer. `sections` and `nav_labels` are never bound here, so the module
    body's loops find an undefined iterable and produce nothing.

    The doctype is asserted as a count, not an absence: edit_sections.html is a
    full page and carries its own.
    """
    assert osiot_html.count("<!doctype") == 1
    for leaked in ("site-header", "site-footer", "nav-links"):
        assert leaked not in osiot_html


def test_the_add_button_is_disabled_with_its_reason_on_a_seeded_database(
    osiot_html
):
    """cp-main-edit-sections.add-section-button stays rendered and visible when
    every kind is already on the page — which is every seeded install, since
    seed_if_empty inserts all six and nothing can be deleted yet."""
    assert "<button type=\"button\" class=\"add-section-button\" disabled>" \
        in osiot_html
    assert element_text(osiot_html, "span", "add-section-reason") == \
        "Kaikki osiotyypit ovat jo sivulla"


def test_the_add_button_offers_the_kinds_that_are_missing(
    logged_in_admin, app
):
    delete_section(app, "sijainti")
    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    assert element_text(html, "button", "add-section-item") == "Sijainti"
    # The reason is rendered on every page and hidden while a kind is still
    # offerable — taking the last one closes the menu with no reload, and
    # the sentence the screen then needs has to already be on it rather than
    # be written in JavaScript. Hidden is what makes that honest, so hidden
    # is what is asserted; test_an_element_rendered_hidden_is_actually_hidden
    # is what stops the stylesheet from drawing it anyway.
    assert '<span class="add-section-reason" hidden>' in html
    assert element_text(html, "span", "add-section-reason") == \
        "Kaikki osiotyypit ovat jo sivulla"


# --- Step 4: the row fragment, and byte-identity back to the page ------------

FRAGMENT_TEXT_CRITERIA = [
    ("cp-main-edit-sections.expanded-editor.exp-title",
     "h3", "exp-title", "Tietoa minusta"),
    ("cp-main-edit-sections.expanded-editor.exp-muokataan",
     "span", "exp-muokataan", "Muokataan"),
    ("cp-main-edit-sections.expanded-editor.exp-sulje",
     "button", "exp-sulje", "Sulje"),
    ("cp-main-edit-sections.expanded-editor.esikatselu-panel.esikatselu-label",
     "p", "esikatselu-label", "ESIKATSELU"),
    # esikatselu-card's other criterion, "Olen työskennellyt puheterapeuttina",
    # is sample data no seeded payload holds — proven live, not by a fixture.
    ("cp-main-edit-sections.expanded-editor.esikatselu-panel.esikatselu-card",
     "div", "esikatselu-card", "TIETOA MINUSTA"),
    (("cp-main-edit-sections.expanded-editor.esikatselu-panel"
      ".esikatselu-disclaimer"),
     "p", "esikatselu-disclaimer", DISCLAIMER),
    ("cp-main-edit-sections.expanded-editor.exp-footer.exp-autosave",
     "span", "exp-autosave", "Automaattitallennus"),
    ("cp-main-edit-sections.expanded-editor.exp-footer.exp-autosave",
     "span", "exp-autosave", "Palauta edellinen versio"),
    ("cp-main-edit-sections.expanded-editor.exp-footer.exp-peruuta",
     "button", "exp-peruuta", "Peruuta"),
    ("cp-main-edit-sections.expanded-editor.exp-footer.exp-tallenna",
     "button", "exp-tallenna", "Tallenna osio"),
]


@pytest.mark.parametrize(
    "address,tag,cls,expected",
    [
        pytest.param(a, t, c, e, id=f"{a}:{e}")
        for a, t, c, e in FRAGMENT_TEXT_CRITERIA
    ],
)
def test_row_fragment_contains_text(
    tietoa_fragment, address, tag, cls, expected
):
    text = element_text(tietoa_fragment, tag, cls)
    assert text is not None, f"{address}: no <{tag} class={cls}> in the fragment"
    assert expected in text, f"{address}: {expected!r} not in {text!r}"


def test_the_expanded_editor_is_rendered_hidden(tietoa_fragment):
    """cp-main-edit-sections.expanded-editor — present in every row's markup,
    collapsed until Muokkaa opens it."""
    assert '<div class="expanded-editor" hidden>' in tietoa_fragment
    assert element_text(tietoa_fragment, "div", "expanded-editor") is not None


def test_both_menus_are_rendered_hidden(tietoa_fragment, logged_in_admin, app):
    """The attribute the CSS guard below is a guard *on*, asserted directly.

    test_an_element_rendered_hidden_is_actually_hidden reads its subjects out
    of these same two templates, so deleting `hidden` from either menu does
    not fail it — the guard silently loses the subject instead. That is the
    exact bug that shipped once: .row-menu-items and .add-section-menu both
    carry `display: flex`, so a menu without the attribute is drawn
    permanently open over the row beneath it. One line each, the same form
    test_the_expanded_editor_is_rendered_hidden already uses.
    """
    assert '<div class="row-menu-items" hidden>' in tietoa_fragment

    # The add menu is only rendered when some kind is missing from the page.
    delete_section(app, "sijainti")
    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    assert '<div class="add-section-menu" hidden>' in html


def test_the_section_form_is_served_empty_for_the_factory_to_fill(
    tietoa_fragment
):
    """The form is generated by section-form.js in both of its placements, so
    the server renders the container and no fields. This is the honest reason
    nostolause-label / leipateksti-label cannot be asserted in pytest."""
    assert '<form class="section-form"></form>' in tietoa_fragment
    assert element_text(tietoa_fragment, "span", "field-label") is None


def test_the_page_row_is_byte_identical_to_the_fragment(
    osiot_html, logged_in_admin, app
):
    """What carries every expanded-editor assertion above back to the page
    document. It is structural rather than lucky: section_row(section) takes
    exactly one argument, and both the page's list loop and _row_fragment.html
    consist of a single call to it. Adding an index argument to any macro in
    _section_row.html breaks this test.
    """
    tietoa = row_id(app, "tietoa")
    fragment = logged_in_admin.get(
        f"/muokkaa/osiot/rivi/{tietoa}"
    ).get_data(as_text=True)
    assert outer_li(osiot_html, tietoa) == fragment.strip()


def test_byte_identity_holds_for_a_row_whose_card_nests_list_items(
    osiot_html, logged_in_admin, app
):
    # hero's fact_card and palvelut's service_card emit <li>, so these rows
    # exercise the depth-aware extractor rather than the flat one.
    for kind in ("hero", "palvelut"):
        section_id = row_id(app, kind)
        fragment = logged_in_admin.get(
            f"/muokkaa/osiot/rivi/{section_id}"
        ).get_data(as_text=True)
        assert outer_li(osiot_html, section_id) == fragment.strip()


# --- Step 2: PUT /api/sections/order -----------------------------------------


def order_body(case, ids):
    """The refused bodies, each built from the real ids the store holds.

    Every id list here is *reversed* first, deliberately. A refused list in
    ascending order would write the positions the rows already have, so an
    endpoint that wrote before it validated would leave the table looking
    untouched and the transactional claim would pass without being tested.
    """
    backwards = list(reversed(ids))
    return {
        # A partial list is a lost row, not a smaller write.
        "partial": {"ids": backwards[:-1]},
        # Right length, but one row named twice and one not at all. Note
        # this is caught by the set-equality check, not the duplicate one —
        # the dropped row is enough on its own.
        "duplicate": {"ids": [backwards[0]] + backwards[1:-1] + [backwards[0]]},
        # Every id present and one of them twice, so the set still matches
        # every known row and only the duplicate check can refuse it. The
        # case that makes that check reachable: without it this body is
        # accepted 200 and writes a seventh position.
        "over-long": {"ids": backwards + [backwards[0]]},
        "unknown-id": {"ids": backwards[:-1] + [9999]},
        "not-a-list": {"ids": "1,2,3"},
        "missing-ids": {},
        "string-ids": {"ids": [str(i) for i in backwards]},
        # bool is an int in Python; it is not a section id.
        "boolean-id": {"ids": [True] + backwards[1:]},
        "not-an-object": ["a", "list", "at", "the", "top", "level"],
    }[case]


NOT_WHOLE = "listassa on oltava jokainen osio täsmälleen kerran"
MALFORMED = "ids puuttuu tai ei ole lista kokonaislukuja"


@pytest.mark.parametrize(
    "case,reason",
    [
        ("partial", NOT_WHOLE),
        ("duplicate", NOT_WHOLE),
        ("over-long", NOT_WHOLE),
        ("unknown-id", NOT_WHOLE),
        ("not-a-list", MALFORMED),
        ("missing-ids", MALFORMED),
        ("string-ids", MALFORMED),
        ("boolean-id", MALFORMED),
        ("not-an-object", MALFORMED),
    ],
)
def test_a_refused_reorder_writes_nothing(logged_in_admin, app, case, reason):
    """The whole order arrives or nothing does. Each refusal is checked against
    the positions the store holds either side, not against the response alone —
    a 400 that had already rewritten half the table would pass otherwise.

    The reason is asserted per case rather than merely being truthy: a body
    that never parsed answers "malformed" too, so a harness that mangled its
    own JSON would otherwise show eight green refusals having tested one.
    """
    before = positions(app)
    body = order_body(case, [r["id"] for r in section_rows(app)])

    response = logged_in_admin.put(
        "/api/sections/order", json=body, headers=JSON_ACCEPT
    )

    assert response.status_code == 400
    assert response.get_json()["error"] == reason
    assert positions(app) == before


def test_the_full_order_reversed_reorders_the_screen_and_the_public_page(
    logged_in_admin, app
):
    before = kinds_in_position_order(app)
    ids = [r["id"] for r in section_rows(app)]

    response = put_order(logged_in_admin, list(reversed(ids)))
    assert response.status_code == 200

    assert kinds_in_position_order(app) == list(reversed(before))
    assert positions(app) == {
        section_id: place
        for place, section_id in enumerate(reversed(ids), start=1)
    }

    # The screen re-reads it …
    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    rendered = re.findall(r'<li class="section-row" data-section-id="(\d+)"',
                          html)
    assert [int(i) for i in rendered] == list(reversed(ids))

    # … and so does the public page, sections and nav both (page.html:110-127).
    public = public_html(app)
    section_order = re.findall(r'<section id="([a-z]+)"', public)
    assert section_order == ["sijainti", "yhteydenotto", "vastaanotto",
                             "palvelut", "tietoa", "hero"]
    nav = element_text(public, "nav", "nav-links")
    assert nav.index("Sijainti") < nav.index("Vastaanotto") < nav.index("Tietoa")


# --- Step 3: add, hide/show, restore -----------------------------------------


def add_kind(logged_in_admin, app, kind):
    """A genuinely absent kind, then really added through the endpoint."""
    delete_section(app, kind)
    response = logged_in_admin.post(
        "/api/sections", json={"kind": kind}, headers=JSON_ACCEPT
    )
    assert response.status_code == 201
    return response.get_json()


@pytest.fixture
def added_sijainti(logged_in_admin, app):
    return add_kind(logged_in_admin, app, "sijainti")


@pytest.mark.parametrize("kind", ["sijainti", "tietoa"])
def test_a_new_section_arrives_hidden_and_never_reaches_the_public_page(
    logged_in_admin, app, kind
):
    """Both kinds, and tietoa is not decoration.

    The stored bytes below are the module's stated convention — json.dumps
    with ensure_ascii=False, so a no-op save reproduces them and the badge's
    draft == published comparison stays honest (app/sectionlist.py:5-10).
    On sijainti alone that assertion cannot fail: its blank payload is
    {"address": ""}, pure ASCII, so ensure_ascii changes not one byte and
    dropping the argument survives it. tietoa's schema has the field name
    "leipäteksti", so the same line is red the moment the convention is
    dropped — which is what makes asserting it worth anything.
    """
    added = add_kind(logged_in_admin, app, kind)
    assert added["state"] == "hidden"
    assert added["badge"] == "Piilotettu"
    assert added["payload"] == blank_payload(kind)

    row = next(r for r in section_rows(app) if r["id"] == added["id"])
    assert row["published"] is None
    assert row["previous_published"] is None
    assert row["draft"] == json.dumps(blank_payload(kind), ensure_ascii=False)
    # Last, after the five that stayed. Stated as the order rather than as
    # position == 6: deleting a middle row leaves its number behind, so the
    # kind decides the literal and the claim never was about the literal.
    assert kinds_in_position_order(app)[-1] == kind

    c = database.connect(app.config["DATABASE"])
    try:
        assert kind not in [s["kind"] for s in visible_sections(c)]
    finally:
        c.close()

    # Off the page and out of the nav: page.html builds both loops from the
    # same visible list, so the anchor is absent from either or from both.
    public = public_html(app)
    assert f'id="{ANCHORS[kind]}"' not in public
    assert f'href="#{ANCHORS[kind]}"' not in public


def test_the_added_row_renders_on_the_screen_with_its_piilotettu_badge(
    added_sijainti, logged_in_admin
):
    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    row = outer_li(html, added_sijainti["id"])
    assert element_text(row, "span", "row-title") == "Sijainti"
    assert element_text(row, "span", "row-status-badge") == "Piilotettu"
    assert element_text(row, "span", "row-summary") == "Osoite"
    # Näytä osio is offered but disabled, with the reason visible.
    assert element_text(row, "span", "row-menu-reason") == "Julkaise osio ensin"


def test_adding_a_section_answers_the_fresh_count_for_the_topbar(
    logged_in_admin, app
):
    """cp-main-edit-sections.sections-count, one scope out from the
    .exp-restore staleness this branch already fixed.

    The add handler appends the new <li> without a reload, so the count the
    document was served with is wrong the moment it lands: "Etusivu · 5
    osiota" over six rows, the spec address asserting a false number until
    someone refreshes. The client is handed the finished string rather than
    told to count, and this asserts it is the SAME string the reloaded
    screen shows — so the two cannot drift and the Finnish plural rule stays
    in one place.

    Both plurals, because the singular is where a rule like this gets got
    wrong and it is reachable from here: five kinds deleted leaves one row,
    and adding one back makes two.
    """
    def topbar():
        return element_text(
            logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True),
            "span", "topbar-page",
        )

    def add(kind):
        response = logged_in_admin.post(
            "/api/sections", json={"kind": kind}, headers=JSON_ACCEPT
        )
        assert response.status_code == 201
        return response.get_json()["page_label"]

    delete_section(app, "sijainti")
    assert topbar() == "Etusivu · 5 osiota"
    assert add("sijainti") == "Etusivu · 6 osiota" == topbar()

    for kind in ("tietoa", "palvelut", "vastaanottoajat", "yhteydenotto",
                 "sijainti"):
        delete_section(app, kind)
    assert topbar() == "Etusivu · 1 osio"
    assert add("sijainti") == "Etusivu · 2 osiota" == topbar()


def test_showing_a_section_with_nothing_published_is_refused(
    added_sijainti, logged_in_admin, app
):
    """The two-click path (Lisää osio → Näytä osio) is closed: the public page
    gates on state alone and falls back to an empty payload, so a row with a
    NULL published column would render as literally nothing."""
    response = logged_in_admin.post(
        f"/api/sections/{added_sijainti['id']}/state",
        json={"state": "published"}, headers=JSON_ACCEPT,
    )
    assert response.status_code == 409
    assert response.get_json()["error"] == "osiolla ei ole julkaistua sisältöä"

    row = next(r for r in section_rows(app) if r["id"] == added_sijainti["id"])
    assert row["state"] == "hidden"  # the refusal wrote nothing
    assert 'id="sijainti"' not in public_html(app)


def test_showing_a_section_whose_published_payload_is_blank_is_refused(
    added_sijainti, logged_in_admin, app
):
    """The three-click path, and the one that actually reaches the empty
    render: Julkaise publishes the new row (its blank draft differs from its
    NULL published), so `published` becomes the blank payload. The gate is on
    content, not on nullness, so the flip is still refused.
    """
    published = publish(logged_in_admin).get_json()["published"]
    assert added_sijainti["id"] in published

    row = next(r for r in section_rows(app) if r["id"] == added_sijainti["id"])
    assert json.loads(row["published"]) == blank_payload("sijainti")

    response = logged_in_admin.post(
        f"/api/sections/{added_sijainti['id']}/state",
        json={"state": "published"}, headers=JSON_ACCEPT,
    )
    assert response.status_code == 409
    assert response.get_json()["error"] == "osion sisältö on tyhjä"

    row = next(r for r in section_rows(app) if r["id"] == added_sijainti["id"])
    assert row["state"] == "hidden"
    public = public_html(app)
    assert 'id="sijainti"' not in public
    assert "SIJAINTI" not in public


def test_a_section_reaches_the_public_page_once_it_has_real_content(
    added_sijainti, logged_in_admin, app
):
    section_id = added_sijainti["id"]
    assert logged_in_admin.put(
        f"/api/sections/{section_id}/draft",
        json={"address": "Kauppakatu 1, Turku"}, headers=JSON_ACCEPT,
    ).status_code == 200
    assert publish(logged_in_admin).status_code == 200

    response = logged_in_admin.post(
        f"/api/sections/{section_id}/state",
        json={"state": "published"}, headers=JSON_ACCEPT,
    )
    assert response.status_code == 200
    assert response.get_json()["badge"] == "Julkaistu"

    public = public_html(app)
    assert 'id="sijainti"' in public
    assert "Kauppakatu 1, Turku" in public


@pytest.mark.parametrize(
    "kind,expected",
    [("kuvagalleria", "tuntematon osiotyyppi"), ("hero", "osiotyyppi on jo sivulla")],
)
def test_add_refuses_an_unknown_kind_and_a_kind_already_present(
    logged_in_admin, app, kind, expected
):
    before = len(section_rows(app))
    response = logged_in_admin.post(
        "/api/sections", json={"kind": kind}, headers=JSON_ACCEPT
    )
    assert response.status_code == 400
    assert response.get_json()["error"] == expected
    assert len(section_rows(app)) == before


def test_an_unknown_state_is_refused(logged_in_admin, app):
    before = section_rows(app)
    response = logged_in_admin.post(
        f"/api/sections/{row_id(app, 'hero')}/state",
        json={"state": "arkistoitu"}, headers=JSON_ACCEPT,
    )
    assert response.status_code == 400
    assert section_rows(app) == before


# --- the badge mapping over the real screen ----------------------------------


def test_a_hidden_section_with_edits_reads_piilotettu_not_luonnos(
    logged_in_admin, app
):
    """The gate claim, stated exactly: LLM-COP-1's mapping has Piilotettu win
    over everything (app/sections.py:12-13), so a hidden row with a dirty draft
    is Piilotettu even though `draft != published`."""
    tietoa = row_id(app, "tietoa")
    assert logged_in_admin.post(
        f"/api/sections/{tietoa}/state", json={"state": "hidden"},
        headers=JSON_ACCEPT,
    ).status_code == 200

    payload = copy.deepcopy(SEED_BY_KIND["tietoa"])
    payload["nostolause"] = "Uusi nostolause, muutettu piilotettuna."
    response = logged_in_admin.put(
        f"/api/sections/{tietoa}/draft", json=payload, headers=JSON_ACCEPT
    )
    assert response.status_code == 200
    assert response.get_json()["badge"] == "Piilotettu"

    row = next(r for r in section_rows(app) if r["id"] == tietoa)
    assert row["draft"] != row["published"]  # genuinely dirty …

    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    scoped = outer_li(html, tietoa)
    assert element_text(scoped, "span", "row-status-badge") == "Piilotettu"
    assert "Luonnos" not in scoped  # … and still not Luonnos


def test_all_three_badges_appear_in_one_served_document(logged_in_admin, app):
    hero, tietoa, palvelut = (row_id(app, k) for k in
                              ("hero", "tietoa", "palvelut"))
    logged_in_admin.post(f"/api/sections/{tietoa}/state",
                         json={"state": "hidden"}, headers=JSON_ACCEPT)
    dirty = copy.deepcopy(SEED_BY_KIND["palvelut"])
    dirty["services"].append("Neljäs palvelu")
    assert logged_in_admin.put(
        f"/api/sections/{palvelut}/draft", json=dirty, headers=JSON_ACCEPT
    ).status_code == 200

    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    badges = {
        kind: element_text(outer_li(html, section_id), "span",
                           "row-status-badge")
        for kind, section_id in (("hero", hero), ("tietoa", tietoa),
                                 ("palvelut", palvelut))
    }
    assert badges == {"hero": "Julkaistu", "tietoa": "Piilotettu",
                      "palvelut": "Luonnos"}
    # And the dirty row's summary followed its payload, not the schema.
    assert element_text(outer_li(html, palvelut), "span", "row-summary") == \
        "4 palvelukorttia"


def test_every_kind_renders_its_own_summary_line(osiot_html, app):
    """Three of the six summaries were rendered but never read: tietoa's,
    vastaanottoajat's and yhteydenotto's could each be replaced with any
    other string and the suite stayed green. All six are pinned here.

    Asserted as literals off the served document rather than against
    summarize(): comparing the renderer to the generator is satisfied by
    any pair of matching mutants, and it is the string a person reads on
    the row that this screen promises.
    """
    rendered = {
        kind: element_text(
            outer_li(osiot_html, row_id(app, kind)), "span", "row-summary"
        )
        for kind in FIELDS
    }
    assert rendered == {
        "hero": HERO_SUMMARY,
        "tietoa": "Nostolause, leipäteksti, 3 faktaa",
        "palvelut": "3 palvelukorttia",
        "vastaanottoajat": "Aukioloajat ja yhteydenottokehotus",
        "yhteydenotto": "Kentät ja kiitosviesti",
        "sijainti": "Osoite",
    }


# --- Palauta edellinen versio ------------------------------------------------


def test_restore_is_refused_while_there_is_no_previous_version(
    logged_in_admin, app, osiot_html
):
    """On a seeded database every row's previous_published is NULL
    (app/seed.py:119), so restore is unavailable until the first Julkaise —
    and the control is rendered disabled rather than hidden."""
    hero = row_id(app, "hero")
    before = section_rows(app)
    assert all(r["previous_published"] is None for r in before)

    response = logged_in_admin.post(
        f"/api/sections/{hero}/restore", headers=JSON_ACCEPT
    )
    assert response.status_code == 409
    assert response.get_json()["error"] == \
        "osiolla ei ole edellistä julkaistua versiota"
    # The whole table either side, not previous_published alone: a refusal
    # that wrote the draft and committed before returning 409 passed the
    # narrower check, which read the one column the write did not touch.
    assert section_rows(app) == before

    scoped = outer_li(osiot_html, hero)
    assert 'class="exp-restore" data-action="restore" disabled' in scoped
    assert element_text(scoped, "button", "exp-restore") == \
        "Palauta edellinen versio"


def test_restore_writes_the_draft_only_and_the_screen_says_a_publish_is_needed(
    logged_in_admin, app
):
    """The claim with teeth: after a restore the public page is unchanged, the
    row reads Luonnos, and the disclaimer beside the editor says so."""
    hero = row_id(app, "hero")
    payload = copy.deepcopy(SEED_BY_KIND["hero"])
    payload["title"] = "Muokattu otsikko"
    assert logged_in_admin.put(
        f"/api/sections/{hero}/draft", json=payload, headers=JSON_ACCEPT
    ).status_code == 200
    assert publish(logged_in_admin).status_code == 200
    assert "Muokattu otsikko" in public_html(app)

    before = next(r for r in section_rows(app) if r["id"] == hero)
    assert before["previous_published"] is not None

    response = logged_in_admin.post(
        f"/api/sections/{hero}/restore", headers=JSON_ACCEPT
    )
    assert response.status_code == 200
    assert response.get_json()["badge"] == "Luonnos"

    after = next(r for r in section_rows(app) if r["id"] == hero)
    assert after["draft"] == before["previous_published"]  # byte-identical
    assert after["published"] == before["published"]  # untouched
    assert after["previous_published"] == before["previous_published"]
    assert after["state"] == before["state"]

    # It did not reach the public page — a restore still needs Julkaise.
    assert "Muokattu otsikko" in public_html(app)

    html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
    scoped = outer_li(html, hero)
    assert element_text(scoped, "span", "row-status-badge") == "Luonnos"
    assert element_text(scoped, "p", "esikatselu-disclaimer") == DISCLAIMER
    assert 'class="exp-restore" data-action="restore">' in scoped  # now enabled


def test_the_row_fragment_enables_restore_as_soon_as_a_publish_lands(
    logged_in_admin, app
):
    """The fragment an open row re-fetches must already say `enabled`.

    THE BUG this is the server half of: refreshRow (app/static/sectionlist.js)
    swaps .row-head and .esikatselu-card out of this fragment and nothing else,
    because .expanded-editor holds the open form. .exp-restore lives in
    .expanded-editor. POST /api/publish is the one call that flips can_restore
    — it is what first fills previous_published — so open a row, edit, Julkaise,
    change your mind, and the restore button was still the disabled one the
    server rendered at page load. The headline one-step restore, dead on screen
    until a reload, in the flow that most wants it.

    What THIS test can honestly prove is the input to that swap: the same
    fragment URL, fetched either side of the publish, must go from disabled to
    enabled. It is a real assertion that can go red (delete can_restore from
    list_rows and it does), and it is a precondition of the fix — but it cannot
    see the swap itself, because nothing in this repository executes
    JavaScript. The client half is guarded statically by
    test_the_row_refresh_carries_the_restore_control_across, and proven for
    real only by the live browser run, which clicks Julkaise and then clicks
    Palauta edellinen versio without reloading.
    """
    hero = row_id(app, "hero")
    url = f"/muokkaa/osiot/rivi/{hero}"

    before = logged_in_admin.get(url).get_data(as_text=True)
    assert 'class="exp-restore" data-action="restore" disabled' in before

    payload = copy.deepcopy(SEED_BY_KIND["hero"])
    payload["title"] = "Muokattu otsikko"
    assert logged_in_admin.put(
        f"/api/sections/{hero}/draft", json=payload, headers=JSON_ACCEPT
    ).status_code == 200
    # Only the publish may flip it: a save leaves previous_published alone, so
    # the fragment a save re-fetches still says disabled and the screen is
    # right to. Asserted, because a fix that enabled the control on any
    # refresh would be wrong here and this is where it would show.
    saved = logged_in_admin.get(url).get_data(as_text=True)
    assert 'class="exp-restore" data-action="restore" disabled' in saved

    assert hero in publish(logged_in_admin).get_json()["published"]
    assert next(
        r for r in section_rows(app) if r["id"] == hero
    )["previous_published"] is not None

    after = logged_in_admin.get(url).get_data(as_text=True)
    assert 'class="exp-restore" data-action="restore">' in after  # enabled
    assert element_text(after, "button", "exp-restore") == \
        "Palauta edellinen versio"


def test_the_menus_derived_state_is_inside_the_subtree_that_is_swapped(
    tietoa_fragment
):
    """Why .exp-restore was the only stale control, stated as an assertion.

    can_show moves on a publish exactly as can_restore does, so the ⋯ menu's
    Näytä osio and its disabled reason are the obvious second casualty — and
    they are not, because .row-menu is rendered inside .row-head and refreshRow
    replaces .row-head whole. That is the entire reason the menu is sound, and
    an unasserted reason is a reason that stops being true. Move the menu out
    beside the editor for layout's sake and this goes red, which is precisely
    when someone needs telling.

    element_text collects a matched element's text with its children included
    (tests/conftest.py:100-124), so the menu's labels showing up in .row-head's
    text is containment, not adjacency.
    """
    head = element_text(tietoa_fragment, "div", "row-head")
    assert "Piilota osio" in head
    assert "Näytä osio" in head

    # The counterpart, and the shape of the defect: the restore control is NOT
    # in there, which is why refreshRow has to carry its flag by hand.
    assert "Palauta edellinen versio" not in head
    assert "Palauta edellinen versio" in element_text(
        tietoa_fragment, "div", "expanded-editor"
    )


def test_the_row_menu_disables_the_action_its_reason_explains(
    added_sijainti, logged_in_admin, app
):
    """cp-section-row's ⋯ menu — the attribute, not only the sentence.

    The reason under Näytä osio was asserted; the `disabled` it explains was
    not, so deleting either conditional from _section_row.html left the whole
    suite green and left the menu offering an action the server can only
    answer 409. Asserted the way .exp-restore already is
    (test_the_row_fragment_enables_restore_as_soon_as_a_publish_lands): the
    rendered attribute, in both directions, so a conditional deleted and a
    conditional inverted are each red.

    Three rows, because two of them cover only one direction each:

    * hero, seeded published — Piilota osio open, Näytä osio closed because
      the row is already shown, and no reason because nothing is wrong.
    * the added sijainti, hidden with a NULL published column — both closed,
      and this is the one that carries a reason.
    * tietoa, published content taken down — Piilota osio closed and Näytä
      osio OPEN, which is the direction the other two cannot show.
    """
    def menu(kind):
        html = logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True)
        return outer_li(html, row_id(app, kind))

    hero = menu("hero")
    assert 'data-action="hide">Piilota osio' in hero
    assert 'data-action="show" disabled>Näytä osio' in hero
    assert element_text(hero, "span", "row-menu-reason") is None

    sijainti = outer_li(
        logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True),
        added_sijainti["id"],
    )
    assert 'data-action="hide" disabled>Piilota osio' in sijainti
    assert 'data-action="show" disabled>Näytä osio' in sijainti
    assert element_text(sijainti, "span", "row-menu-reason") == \
        "Julkaise osio ensin"

    assert logged_in_admin.post(
        f"/api/sections/{row_id(app, 'tietoa')}/state",
        json={"state": "hidden"}, headers=JSON_ACCEPT,
    ).status_code == 200
    tietoa = menu("tietoa")
    assert 'data-action="hide" disabled>Piilota osio' in tietoa
    assert 'data-action="show">Näytä osio' in tietoa
    assert element_text(tietoa, "span", "row-menu-reason") is None


def test_restoring_a_hidden_row_leaves_it_hidden(logged_in_admin, app):
    """The same non-mutation claim in the only direction that can fail.

    seed_if_empty inserts every row state='published', and the test above
    restores hero, so its `after["state"] == before["state"]` holds for a row
    that was never anything but published — it cannot catch a restore that
    republishes. This one restores a row *while it is hidden*: a restore that
    wrote `state = 'published'` alongside the draft would silently put a
    section the author had taken down back on the public page, and a badge
    computed from a hardcoded "published" rather than the row's own state
    would tell them it had not.
    """
    tietoa = row_id(app, "tietoa")
    assert logged_in_admin.post(
        f"/api/sections/{tietoa}/state", json={"state": "hidden"},
        headers=JSON_ACCEPT,
    ).status_code == 200

    payload = copy.deepcopy(SEED_BY_KIND["tietoa"])
    payload["nostolause"] = "Uusi nostolause, muutettu piilotettuna."
    assert logged_in_admin.put(
        f"/api/sections/{tietoa}/draft", json=payload, headers=JSON_ACCEPT
    ).status_code == 200
    # Julkaise is what gives the row a previous_published to restore; it
    # publishes the dirty draft without touching state, so the row is still
    # hidden and still off the public page.
    assert tietoa in publish(logged_in_admin).get_json()["published"]

    before = next(r for r in section_rows(app) if r["id"] == tietoa)
    assert before["state"] == "hidden"
    assert before["previous_published"] is not None

    response = logged_in_admin.post(
        f"/api/sections/{tietoa}/restore", headers=JSON_ACCEPT
    )
    assert response.status_code == 200
    # The badge follows the row's own state, not the state a restore might
    # wish the row were in.
    assert response.get_json()["badge"] == "Piilotettu"

    after = next(r for r in section_rows(app) if r["id"] == tietoa)
    assert after["state"] == "hidden"  # a restore is not a publish
    assert after["draft"] == before["previous_published"]  # byte-identical
    assert after["published"] == before["published"]  # untouched
    assert after["previous_published"] == before["previous_published"]

    # Still off the public page, and the screen still says Piilotettu.
    public = public_html(app)
    assert 'id="tietoa"' not in public
    assert "Uusi nostolause, muutettu piilotettuna." not in public
    scoped = outer_li(
        logged_in_admin.get("/muokkaa/osiot").get_data(as_text=True), tietoa
    )
    assert element_text(scoped, "span", "row-status-badge") == "Piilotettu"


def test_restore_then_julkaise_puts_back_the_exact_published_bytes(
    logged_in_admin, app
):
    """The artifact's own reviewer check. previous_published is copied
    verbatim rather than re-validated and re-serialized, so the round trip is
    byte-for-byte, "ä" and "·" included."""
    hero = row_id(app, "hero")
    seeded_text = json.dumps(SEED_BY_KIND["hero"], ensure_ascii=False)
    assert "ä" in seeded_text and "·" in seeded_text

    payload = copy.deepcopy(SEED_BY_KIND["hero"])
    payload["title"] = "Muokattu otsikko"
    logged_in_admin.put(f"/api/sections/{hero}/draft", json=payload,
                        headers=JSON_ACCEPT)
    publish(logged_in_admin)
    logged_in_admin.post(f"/api/sections/{hero}/restore", headers=JSON_ACCEPT)
    assert publish(logged_in_admin).status_code == 200

    row = next(r for r in section_rows(app) if r["id"] == hero)
    assert row["published"] == seeded_text
    assert SEED_BY_KIND["hero"]["title"] in public_html(app)
    assert "Muokattu otsikko" not in public_html(app)


# --- one renderer each: guards on the duplication the artifact names ---------


ROOT = pathlib.Path(__file__).resolve().parent.parent
JINJA_COMMENT = re.compile(r"\{#.*?#\}", re.DOTALL)


RENDERER_WORDS = ("palvelukort", "Muotokuva, otsikko", "faktaa",
                  "Aukioloajat", "Kentät ja", "service-card", "fact-card",
                  "section-kicker", "about-lead", "hours-row")


def test_no_summary_string_or_public_markup_is_reimplemented_here():
    """app/summary.py is the only place a row summary exists and page.html the
    only place section markup does. Both come back from the row fragment after
    every mutation, so nothing in the client needs either — and this fails the
    moment somebody reimplements one there, which is the artifact's own named
    hazard ("fork the container, not the form") applied to the other two
    renderers.

    This unit's two templates are read alongside the client, because they are
    the other place the duplication would land: `{{ public[section.kind](
    section.payload) }}` in _section_row.html is one subscript, and writing
    the six cards out by hand instead is a change of exactly that one line.
    The negative alone cannot see that, though — hand-written markup that
    used none of these class names would pass it — so it is paired with
    test_the_preview_card_is_the_public_macros_own_output below.
    """
    sources = sorted((ROOT / "app" / "static").glob("*.js")) + [
        ROOT / "app" / "templates" / "edit_sections.html",
        ROOT / "app" / "templates" / "_section_row.html",
    ]
    for path in sources:
        text = path.read_text(encoding="utf-8")
        for word in RENDERER_WORDS:
            assert word not in text, f"{word!r} reimplemented in {path.name}"


def test_the_preview_card_is_the_public_macros_own_output(tietoa_fragment):
    """cp-main-edit-sections.expanded-editor.esikatselu-panel.esikatselu-card
    — the positive half, and the one that makes the guard above bite.

    The card's only other pytest criterion is "TIETOA MINUSTA", which
    _section_row.html writes itself as .esikatselu-kicker; it is green for a
    card whose body is hand-written markup, or none at all. So assert the
    body is page.html's tietoa macro by its own structure: the <section> the
    macro opens, with the id and the class it gives it, and the two element
    classes inside it. Replace the subscript with markup of your own and this
    goes red.

    Structure, never persona text: the sentences inside these elements are
    seeded copy that LLM-COP-10 is removing, and an assertion on them would
    be a test of that unit's data. `data-section=""` is asserted with the
    open tag because the macro takes sid='' when called with one argument —
    which is the whole reason the row and the fragment stay byte-identical.
    """
    card = element_text(tietoa_fragment, "div", "esikatselu-card")
    assert card is not None

    body = tietoa_fragment[tietoa_fragment.index('class="esikatselu-card"'):]
    assert '<section id="tietoa" class="about" data-section=""' in body
    for structural in ("about-columns", "about-lead", "about-body",
                       "about-facts"):
        assert structural in body, structural


@pytest.mark.parametrize(
    "name",
    ["app/templates/edit_sections.html", "app/templates/_section_row.html",
     "app/templates/_row_fragment.html"],
)
def test_no_section_list_template_binds_sections_or_nav_labels(name):
    """Binding either name into a template that imports page.html executes the
    public page's module body for real: with `sections` bound it dereferences
    nav_labels and 500s every render, and with both bound every row emits the
    whole public page as discarded output and raises on a blank payload.
    Comments are stripped first — the constraint is written down in them."""
    code = JINJA_COMMENT.sub("", (ROOT / name).read_text(encoding="utf-8"))
    assert "nav_labels" not in code, name
    assert "in sections" not in code, name


def test_the_blueprint_never_passes_sections_or_nav_labels_to_a_template():
    """The same constraint on the Python side, read off the call sites rather
    than off the text: app/edit.py:48 already binds this very list as
    `sections=sections` for edit.html, so copying that line is the obvious
    move and it 500s every render of the new screen."""
    tree = ast.parse((ROOT / "app" / "sectionlist.py").read_text(
        encoding="utf-8"))
    passed = {
        keyword.arg
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        for keyword in node.keywords
    }
    assert "sections" not in passed
    assert "nav_labels" not in passed


# --- this screen's grip on the two shared modules ----------------------------
#
# Why these exist at all: before them, `grep -rn "sectionlist.js\|edit_sections"
# tests/` answered nothing, so the whole suite stayed green with the inline
# editor completely dead. That is not a hypothetical — this branch was rebased
# onto a main that had extracted the form builder and the debounce, and both a
# missing <script> tag and a factory contract that no longer existed survived a
# branch already called proven and reviewed. The two sibling hosts of these
# modules each carry a standing guard (tests/test_wizard.py:602 and :616);
# this, the third host, carried none.
#
# The parser and the comment stripper below are deliberately local copies
# rather than shared with tests/test_wizard.py: that file belongs to another
# unit and a helper moved into tests/conftest.py would be a third unit editing
# a file two others are already appending to.


def document_scripts(html):
    """Every <script> of the document in source order: an inline one by its
    id, an external one by its filename.

    The inline #bootstrap blob is included because it, too, is load-bearing
    order — sectionlist.js reads document.getElementById("bootstrap") at parse
    time, so a bootstrap moved below it throws before a single row is wired."""

    class _Scripts(HTMLParser):
        def __init__(self):
            super().__init__(convert_charrefs=True)
            self.names = []

        def handle_starttag(self, tag, attrs):
            if tag != "script":
                return
            attributes = dict(attrs)
            src = attributes.get("src")
            if src:
                self.names.append(src.rsplit("/", 1)[-1])
            elif attributes.get("id"):
                self.names.append(attributes["id"])

    parser = _Scripts()
    parser.feed(html)
    return parser.names


# Strings first, so a "//" inside one is eaten as string and never mistaken
# for a comment. No file here uses a regex literal, which this would misread.
JS_STRING_OR_COMMENT = re.compile(
    r'"(?:\\.|[^"\\])*"'
    r"|'(?:\\.|[^'\\])*'"
    r"|`(?:\\.|[^`\\])*`"
    r"|/\*.*?\*/"
    r"|//[^\n]*",
    re.DOTALL,
)


def strip_js_comments(source):
    """The source with comments blanked and every newline kept, so offsets
    stay on their own lines. Required because sectionlist.js's header comment
    names window.createSectionForm and window.createAutosave.DELAY in prose,
    and a guard that reads prose is a guard that cannot fail."""

    def blank(match):
        text = match.group(0)
        if text.startswith(("/*", "//")):
            return "\n" * text.count("\n")
        return text

    return JS_STRING_OR_COMMENT.sub(blank, source)


def read_js(name):
    return (ROOT / "app" / "static" / name).read_text(encoding="utf-8")


def test_the_section_list_screen_loads_the_shared_modules_before_its_own(
    osiot_html,
):
    """Mandatory, not stylistic, and the guard this screen was missing.

    Opening a row calls window.createSectionForm (section-form.js), which
    reaches window.createRichEditor (editor.js) for hero's rich ingress, and
    the row's debounce is window.createAutosave (autosave.js). Any other order
    throws on load and not one row ever expands — which is exactly the state
    this branch shipped in after its rebase, with 410 tests green.

    Asserted as the whole ordered list rather than as pairwise precedence
    because this template is this unit's own: a script silently dropped is the
    breakage that actually happened, and a precedence-only check passes when a
    file is missing entirely.

    Read off the SERVED document, not the template file: what a browser
    executes is what url_for resolved and Jinja emitted."""
    names = document_scripts(osiot_html)
    assert names == [
        "bootstrap",
        "editor.js",
        "autosave.js",
        "section-form.js",
        "sectionlist.js",
    ], names


def test_the_section_list_reads_the_shared_autosave_delay():
    """The positive form, and it has to be the positive form.

    tests/test_wizard.py:632 proves the literal 2000 lives in autosave.js and
    nowhere else — but that test is green for a host with no debounce at all,
    which is precisely what this file would have been had the rewire been
    dropped. So assert what the host must actually do: build the shared
    debounce, and read the delay from the module that declares it."""
    source = strip_js_comments(read_js("sectionlist.js"))
    assert "window.createAutosave(" in source
    assert "window.createAutosave.DELAY" in source


def test_the_section_list_owns_no_debounce_of_its_own():
    """The other half: reading the shared constant proves nothing if the file
    also keeps a hand-rolled setTimeout beside it. sectionlist.js legitimately
    owns no timer — unlike edit.js, whose peruutaTimer is its own — so a bare
    absence check here is honest rather than the false-red it would be there
    (tests/test_wizard.py:655 makes the same distinction for wizard.js)."""
    assert "setTimeout" not in strip_js_comments(read_js("sectionlist.js"))


def statement_calls(source, name):
    """Every `name(` in `source`, each answered as (is_bare_statement, line).

    A bare statement is a call whose value is discarded: preceded by `;`, `{`
    or `}` (or nothing) and followed, past its own closing paren, by `;`. A
    call bound to a variable, returned, or chained onto with `.` is not."""
    results = []
    for match in re.finditer(re.escape(name) + r"\s*\(", source):
        before = source[: match.start()].rstrip()
        opens_at = source.index("(", match.start())
        depth = 0
        index = opens_at
        while index < len(source):
            if source[index] == "(":
                depth += 1
            elif source[index] == ")":
                depth -= 1
                if depth == 0:
                    break
            index += 1
        after = source[index + 1:].lstrip()
        bare = (not before or before[-1] in ";{}") and after.startswith(";")
        results.append((bare, source.count("\n", 0, match.start()) + 1))
    return results


def test_the_section_list_never_uses_a_return_value_from_the_form_builder():
    """main's createSectionForm returns nothing (app/static/section-form.js:246
    ends the function with no return). The factory this branch originally wrote
    returned a handle — payload(), setPayload(), showErrors(), clearErrors(),
    container — and code written against that handle reads perfectly and dies
    at the first property access.

    So: every call here must be an expression statement whose value is thrown
    away. Stated as a limitation rather than left implied — this catches the
    value being BOUND or CHAINED, which is the shape the dead contract takes;
    it cannot catch a handle smuggled out some other way, and nothing static
    could."""
    source = strip_js_comments(read_js("sectionlist.js"))
    calls = statement_calls(source, "window.createSectionForm")
    assert calls, "sectionlist.js no longer calls the shared form builder"
    assert all(bare for bare, _ in calls), [
        line for bare, line in calls if not bare
    ]


def function_body(source, name):
    """The text of `function name(...) { … }`, brace-matched.

    The same depth walk outer_li does, for the same reason: refreshRow holds a
    nested arrow-free callback and two object literals, so a naive scan to the
    first `}` ends the body three lines in. Comments are blanked before this
    runs; no string literal in this file contains a brace.
    """
    start = source.index("function " + name + "(")
    depth = 0
    for index in range(source.index("{", start), len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start:index + 1]
    raise AssertionError(f"unclosed body for {name}")


def test_the_row_refresh_carries_the_restore_control_across():
    """The client half of the stale-restore defect, guarded as far as static
    reading can guard it.

    refreshRow swaps .row-head and .esikatselu-card and deliberately leaves
    .expanded-editor alone — swapping the whole <li> would destroy the open
    form, its focus and the draft object the shared builder is bound to. That
    is right, and it is why .exp-restore, which lives in .expanded-editor, kept
    the disabled state the server rendered at page load: after the Julkaise
    that first creates a previous_published, the fragment said enabled and the
    screen said disabled.

    Three claims, each of which was false before the fix: refreshRow carries
    the flag, it still does not replace .expanded-editor, and the flag is
    COPIED off the fresh fragment rather than worked out here — the server
    stays the only place can_restore is decided, as it is for the badge and the
    summary. What this cannot see is a browser: that the carried flag reaches
    the on-screen button, and that clicking it restores, is the live run's,
    named in test_the_row_fragment_enables_restore_as_soon_as_a_publish_lands.
    """
    source = strip_js_comments(read_js("sectionlist.js"))
    refresh = function_body(source, "refreshRow")
    assert ".row-head" in refresh
    assert ".esikatselu-card" in refresh
    assert "carryRestoreState(" in refresh
    # Still not swapped wholesale — the open form has to survive a publish.
    assert "expanded-editor" not in refresh

    carry = function_body(source, "carryRestoreState")
    # Both sides: the button on screen and the button in the fresh fragment.
    assert carry.count('".exp-restore"') == 2, carry
    # Both sides NAMED, and in this order. `\w+.disabled = \w+.disabled`
    # matched `source.disabled = button.disabled` just as happily — the
    # transposition writes the screen's stale flag onto the fragment that is
    # about to be discarded, which is the defect this fix removed, reinstated
    # and passing.
    assert re.search(r"button\.disabled\s*=\s*source\.disabled\b", carry), carry

    # Copied, not derived. The names the server computes the flag from must
    # not appear here at all; a client that re-derived it would drift.
    assert "previous_published" not in source
    assert "can_restore" not in source


def test_the_add_handler_refreshes_the_topbar_and_the_add_control():
    """The client half of the add's own staleness, guarded as far as static
    reading can guard it.

    Two things outside the appended <li> go stale the moment a section is
    added: the topbar's count, and the add control once the last offerable
    kind is taken. Both are the server's answers here — the count arrives as
    a finished string on the add response, the reason is server-rendered and
    merely unhidden — so what this asserts is that neither is COMPOSED in
    JavaScript. A client that reimplemented the Finnish plural, or typed the
    sentence out, would drift from app/sectionlist.py and
    app/templates/edit_sections.html the first time either changed.

    Both sides of each assignment are named, for the reason finding 5 of the
    review gives: a bare `\\w+.textContent = \\w+.page_label` matches the
    transposition as happily as the fix. What this cannot see is a browser —
    that the written string reaches the screen and that the reason becomes
    visible is the live run's.
    """
    source = strip_js_comments(read_js("sectionlist.js"))

    add = function_body(source, "addSection")
    assert re.search(
        r"topbarPage\.textContent\s*=\s*data\.page_label\b", add
    ), add
    assert "closeAddIfEmpty(" in add

    close = function_body(source, "closeAddIfEmpty")
    assert re.search(r"addButton\.disabled\s*=\s*true\b", close), close
    assert re.search(r"addReason\.hidden\s*=\s*false\b", close), close

    # Carried, not composed. Neither the plural rule nor the sentence may
    # exist in this file; "osiota" would be half a plural rule and
    # "Kaikki osiotyypit" the whole of a second copy of the reason.
    assert "Etusivu" not in source
    assert "osiota" not in source
    assert "Kaikki osiotyypit" not in source


# --- the hidden attribute has to mean something ------------------------------


def css_rules(text):
    """(selector list, declaration block) for every rule, comments stripped."""
    body = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    rules = []
    for chunk in body.split("}"):
        if "{" not in chunk:
            continue
        selectors, declarations = chunk.split("{", 1)
        rules.append((selectors.strip(), declarations.strip()))
    return rules


JINJA_TAG = re.compile(r"\{%.*?%\}|\{\{.*?\}\}", re.DOTALL)


def hidden_classes(template):
    """Every class on an element this unit server-renders with `hidden`.

    Jinja tags are stripped before the parse, and that is load-bearing rather
    than tidy. `class="add-section-reason"{% if offerable %} hidden{% endif %}`
    reaches HTMLParser as the attribute `hidden{%` — the attribute-name
    pattern runs on to the brace — so an element hidden on a CONDITION was
    invisible to this guard while an unconditionally hidden one was not.
    Stripping the tags reads both the same way, which is the conservative
    reading: an element that is ever rendered hidden needs the stylesheet to
    mean it.

    Raises rather than returning an empty set. The guard below derives its
    subjects from the very templates it protects, so a template that renders
    nothing hidden any more makes the guard vacuous instead of red — the
    failure mode the two menus already demonstrated. Both templates hold at
    least one hidden element by design (the expanded editor, the add menu),
    so none is a fact worth reporting quietly.
    """

    class _Hidden(HTMLParser):
        def __init__(self):
            super().__init__(convert_charrefs=True)
            self.classes = set()

        def handle_starttag(self, tag, attrs):
            attributes = dict(attrs)
            if "hidden" in attributes:
                self.classes.update((attributes.get("class") or "").split())

    parser = _Hidden()
    source = (ROOT / template).read_text(encoding="utf-8")
    parser.feed(JINJA_TAG.sub("", JINJA_COMMENT.sub("", source)))
    assert parser.classes, f"{template} renders nothing hidden — the guard" \
        " built from it would assert nothing"
    return parser.classes


def test_an_element_rendered_hidden_is_actually_hidden():
    """An author `display:` beats the UA sheet's `[hidden] { display: none }`
    whatever its specificity, so a stylesheet that gives such an element a
    display and never mentions [hidden] silently un-hides it.

    This is not theoretical. It shipped: .row-menu-items and
    .add-section-menu both set `display: flex`, so all six row menus were
    drawn permanently open, each one covering the right-hand end of the row
    beneath it. Five of the six rows' Muokkaa and ⋯ buttons were unclickable
    with a real mouse, and toggleMenu's `hidden = !opening` changed nothing
    on screen. Every server-side test passed throughout, because none of them
    computes a style — this one reads the rule instead.
    """
    css = css_rules((ROOT / "app" / "static" / "sections.css").read_text(
        encoding="utf-8"))
    blanket = any(
        selector.strip() == "[hidden]" and "display: none" in declarations
        for selector, declarations in css
    )
    styled = set()
    guarded = set()
    for selector, declarations in css:
        display = re.search(r"display:\s*([\w-]+)", declarations)
        for part in selector.split(","):
            part = part.strip()
            match = re.fullmatch(r"\.([\w-]+)(\[hidden\])?", part)
            if not match:
                continue
            name, on_hidden = match.group(1), match.group(2)
            if on_hidden:
                if display and display.group(1) == "none":
                    guarded.add(name)
            elif display and display.group(1) != "none":
                styled.add(name)

    rendered_hidden = hidden_classes(
        "app/templates/_section_row.html"
    ) | hidden_classes("app/templates/edit_sections.html")
    unhidden = sorted((styled & rendered_hidden) - guarded) if not blanket else []
    assert not unhidden, (
        f"{unhidden} are rendered with `hidden` but given a display that"
        " overrides it"
    )


def test_the_shared_form_builder_really_does_return_nothing():
    """The premise of the test above, checked against the module rather than
    assumed — if main's factory ever starts handing back a handle, the guard
    above becomes a rule with no reason and should be revisited, not deleted.
    app/static/section-form.js is outside this unit's diff; this only reads
    it."""
    source = strip_js_comments(read_js("section-form.js"))
    body = source[source.index("function createSectionForm"):]
    body = body[: body.index("window.createSectionForm = createSectionForm")]
    assert not re.search(r"\breturn\s+(?!;)", body[body.index("mount.text"):])
